# Generated by Django 5.1.3 on 2024-12-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration',
            field=models.PositiveIntegerField(choices=[(60, '۱ ساعت'), (90, '۱.۵ ساعت'), (120, '۲ ساعت'), (150, '۲.۵ ساعت'), (180, '۳ ساعت')], default=60, verbose_name='مدت زمان (دقیقه)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='ساعت پایان'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(verbose_name='ساعت شروع'),
        ),
    ]
